-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 14:43:25 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Archive
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Archive` ;

-- -----------------------------------------------------
-- Schema Archive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Archive` ;
USE `Archive` ;

-- -----------------------------------------------------
-- Table `Archive`.`domain_organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`domain_organisation` ;

CREATE TABLE IF NOT EXISTS `Archive`.`domain_organisation` (
  `idDomain_Organisation` INT NOT NULL AUTO_INCREMENT,
  `Domain_Organisation_label_fr` VARCHAR(45) NULL,
  `Domain_Organisation_label_ar` VARCHAR(45) NULL,
  `Domain_Organisation_acronym_fr` VARCHAR(45) NULL,
  `Domain_Organisation_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idDomain_Organisation`),
  UNIQUE INDEX `idDomain_Organisation_UNIQUE` (`idDomain_Organisation` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`region` ;

CREATE TABLE IF NOT EXISTS `Archive`.`region` (
  `idRegion` INT NOT NULL AUTO_INCREMENT,
  `region_label_fr` VARCHAR(45) NULL,
  `region_label_ar` VARCHAR(45) NULL,
  `region_acronym_fr` VARCHAR(45) NULL,
  `region_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`sector` ;

CREATE TABLE IF NOT EXISTS `Archive`.`sector` (
  `idSector` INT NOT NULL AUTO_INCREMENT,
  `label_sector_fr` VARCHAR(45) NULL,
  `label_sector_ar` VARCHAR(45) NULL,
  `acronym_sector_fr` VARCHAR(45) NULL,
  `acronym_sector_ar` VARCHAR(45) NULL,
  `region_ref_id` INT NULL,
  PRIMARY KEY (`idSector`),
  INDEX `fk_Sector_1_idx` (`region_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sector_1`
    FOREIGN KEY (`region_ref_id`)
    REFERENCES `Archive`.`region` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`organisation` ;

CREATE TABLE IF NOT EXISTS `Archive`.`organisation` (
  `id_Organisation` INT NOT NULL AUTO_INCREMENT,
  `Organisation_name_ar` VARCHAR(255) NULL,
  `Organisation_name_fr` VARCHAR(255) NULL,
  `ACRONYM_AR` VARCHAR(45) NULL,
  `ACRONYM_FR` VARCHAR(45) NULL,
  `Organisation_domain_id_ref` INT NULL,
  `sector_ref_id` INT NULL,
  `first_creation_date` DATE NULL,
  `recent_date_creation` DATE NULL,
  `archive_in_theory` TINYINT NULL,
  `archive_stamp` TINYINT NULL,
  `theoretical_staff` INT NULL,
  `actual_staff` INT NULL,
  `theoritical_equipment` VARCHAR(255) NULL,
  `actual_equipment` VARCHAR(255) NULL,
  `has_archive_room` TINYINT NULL,
  `room_adequate` TINYINT NULL,
  `chair_count` INT NULL,
  `sorting_table_count` INT NULL,
  `work_desk_count` INT NULL,
  `photocopier_count` INT NULL,
  `computer_count` INT NULL,
  `printer_count` INT NULL,
  `scanner_count` INT NULL,
  `has_inspection_program` TINYINT NULL,
  `inspection_program_reference` VARCHAR(45) NULL,
  `has_internal_monitoring` TINYINT NULL,
  `monitoring_reference` VARCHAR(45) NULL,
  `archive_under_monitoring` TINYINT NULL,
  `services_organize_archive` TINYINT NULL,
  `services_submit_to_archive` TINYINT NULL,
  `submission_model` TINYINT NULL,
  `fire_protection` TINYINT NULL,
  `theft_protection` TINYINT NULL,
  `water_protection` TINYINT NULL,
  `pest_protection` TINYINT NULL,
  `dust_protection` TINYINT NULL,
  `pack_count` INT NULL,
  `archive_box_count` INT NULL,
  `map_plan_count` INT NULL,
  `card_count` INT NULL,
  `registry_count` INT NULL,
  `electronic_media_count` INT NULL,
  `Organisation_position` VARCHAR(45) NULL,
  `has_classified_data` TINYINT NULL,
  `has_work_documents` TINYINT NULL,
  `has_security_equipment` TINYINT NULL,
  `security_equipment_adequat` TINYINT NULL,
  `does_annuary_migration` TINYINT NULL,
  `work_documents_summarized` TINYINT NULL,
  `work_documents_organized` TINYINT NULL,
  `org_head_title_ar` VARCHAR(255) NULL,
  `org_head_title_fr` VARCHAR(255) NULL,
  `org_head_title_en` VARCHAR(255) NULL,
  `organisation_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `organisation_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `parent_org` INT NULL,
  `organisation_state` ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'MERGED', 'DISSOLVED') NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`id_Organisation`),
  INDEX `fk_Organisation_1_idx` (`Organisation_domain_id_ref` ASC) VISIBLE,
  INDEX `fk_Organisation_2_idx` (`sector_ref_id` ASC) VISIBLE,
  UNIQUE INDEX `id_Organisation_UNIQUE` (`id_Organisation` ASC) VISIBLE,
  CONSTRAINT `fk_Organisation_1`
    FOREIGN KEY (`Organisation_domain_id_ref`)
    REFERENCES `Archive`.`domain_organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organisation_2`
    FOREIGN KEY (`sector_ref_id`)
    REFERENCES `Archive`.`sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organisation_parent`
    FOREIGN KEY (`id_Organisation`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`store` ;

CREATE TABLE IF NOT EXISTS `Archive`.`store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `Storetype` VARCHAR(45) NULL,
  `store_label_fr` VARCHAR(45) NULL,
  `store_label_ar` VARCHAR(45) NULL,
  `store_acronym_fr` VARCHAR(45) NULL,
  `store_acronym_ar` VARCHAR(45) NULL,
  `org_ref` INT NULL,
  `store_type` ENUM('ARCHIVE', 'OFFICE', 'STORAGE', 'COMMON', 'OPEN_WORLD') NULL DEFAULT 'OFFICE',
  PRIMARY KEY (`idStore`),
  INDEX `fk_store_org_idx` (`org_ref` ASC) VISIBLE,
  CONSTRAINT `fk_store_org`
    FOREIGN KEY (`org_ref`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`bay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`bay` ;

CREATE TABLE IF NOT EXISTS `Archive`.`bay` (
  `idBay` INT NOT NULL AUTO_INCREMENT,
  `Store_ref_id` INT NULL,
  `Bay_ref_fr` VARCHAR(45) NULL,
  `Bay_ref_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idBay`),
  INDEX `fk_Bay_1_idx` (`Store_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bay_1`
    FOREIGN KEY (`Store_ref_id`)
    REFERENCES `Archive`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`budget` ;

CREATE TABLE IF NOT EXISTS `Archive`.`budget` (
  `id_budget` INT NOT NULL AUTO_INCREMENT,
  `budget_year` DATE NULL,
  `budget_to_org_ref` INT NULL,
  `budget_type` VARCHAR(45) NULL,
  `budget_org` INT NULL,
  PRIMARY KEY (`id_budget`),
  INDEX `fk_budget_1_idx` (`budget_org` ASC) VISIBLE,
  CONSTRAINT `fk_budget_1`
    FOREIGN KEY (`budget_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`paragraph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`paragraph` ;

CREATE TABLE IF NOT EXISTS `Archive`.`paragraph` (
  `id_paragraph` INT NOT NULL AUTO_INCREMENT,
  `paragraph_desc` VARCHAR(45) NULL,
  `paragraph_budget` DOUBLE NULL,
  `paragraph_consumed_budget` DOUBLE NULL,
  `budget_ref` INT NULL,
  PRIMARY KEY (`id_paragraph`),
  INDEX `fk_paragraph_1_idx` (`budget_ref` ASC) VISIBLE,
  CONSTRAINT `fk_paragraph_1`
    FOREIGN KEY (`budget_ref`)
    REFERENCES `Archive`.`budget` (`id_budget`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`invoice` ;

CREATE TABLE IF NOT EXISTS `Archive`.`invoice` (
  `id_invoice` INT NOT NULL AUTO_INCREMENT,
  `invoice_total` DOUBLE NULL,
  `invoice_date` DATE NULL,
  `invoice_paragraph` INT NULL,
  PRIMARY KEY (`id_invoice`),
  INDEX `fk_invoice_1_idx` (`invoice_paragraph` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_1`
    FOREIGN KEY (`invoice_paragraph`)
    REFERENCES `Archive`.`paragraph` (`id_paragraph`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`component` ;

CREATE TABLE IF NOT EXISTS `Archive`.`component` (
  `id_component` INT NOT NULL AUTO_INCREMENT,
  `component_name_ar` VARCHAR(255) NULL,
  `component_name_fr` VARCHAR(255) NULL,
  `component_type` VARCHAR(45) NULL,
  `component_mission_ar` VARCHAR(255) NULL,
  `component_mission_fr` VARCHAR(255) NULL,
  `component_parent` INT NULL,
  `component_org` INT NULL,
  `component_ending_date` DATE NULL,
  `component_starting_date` DATE NULL,
  `component_head` INT NULL,
  `component_members` INT NULL,
  PRIMARY KEY (`id_component`),
  INDEX `fk_component_1_idx` (`component_parent` ASC) VISIBLE,
  INDEX `fk_component_2_idx` (`component_org` ASC) VISIBLE,
  CONSTRAINT `fk_component_1`
    FOREIGN KEY (`component_parent`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_2`
    FOREIGN KEY (`component_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`profile_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`profile_rank` ;

CREATE TABLE IF NOT EXISTS `Archive`.`profile_rank` (
  `idprofile_rank` INT NOT NULL AUTO_INCREMENT,
  `profile_rank_label_fr` VARCHAR(45) NULL,
  `profile_rank_label_ar` VARCHAR(45) NULL,
  `profile_rank_acronym_fr` VARCHAR(45) NULL,
  `profile_rank_acronym_ar` VARCHAR(45) NULL,
  `profile_rank_acronym_en` VARCHAR(45) NULL,
  `profile_rank_label_en` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofile_rank`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`person` ;

CREATE TABLE IF NOT EXISTS `Archive`.`person` (
  `PERSON_ID` INT NOT NULL AUTO_INCREMENT,
  `Person_name_ar` VARCHAR(255) NULL,
  `Person_lastname_ar` VARCHAR(255) NULL,
  `Person_name_latin` VARCHAR(255) NULL,
  `Person_lastname_latin` VARCHAR(255) NULL,
  PRIMARY KEY (`PERSON_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`career_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`career_profile` ;

CREATE TABLE IF NOT EXISTS `Archive`.`career_profile` (
  `idProfile` INT NOT NULL AUTO_INCREMENT,
  `Profile_serial` VARCHAR(45) NULL,
  `Profile_rank_id_ref` INT NULL,
  `Profile_position_org` INT NULL,
  `Profile_domain_id_ref` INT NULL,
  `designation_reference` VARCHAR(45) NULL,
  `installation_reference` VARCHAR(45) NULL,
  `employment_date` DATE NULL,
  `employee_class` VARCHAR(45) NULL,
  `employee_degree` VARCHAR(45) NULL,
  `last_promotion_date` DATE NULL,
  `degree` VARCHAR(255) NULL,
  `contract_nature` VARCHAR(45) NULL,
  `career_profile_availability` ENUM('active', 'inactive', 'on_leave','transferred', 'retired', 'suspended') NULL DEFAULT 'active',
  `career_profile_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `career_profile_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `person_PERSON_ID` INT NOT NULL,
  PRIMARY KEY (`idProfile`),
  INDEX `fk_Profile_1_idx` (`Profile_rank_id_ref` ASC) VISIBLE,
  INDEX `fk_Profile_2_idx` (`Profile_position_org` ASC) VISIBLE,
  INDEX `fk_Profile_3_idx` (`Profile_domain_id_ref` ASC) VISIBLE,
  INDEX `fk_career_profile_person1_idx` (`person_PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_1`
    FOREIGN KEY (`Profile_rank_id_ref`)
    REFERENCES `Archive`.`profile_rank` (`idprofile_rank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_2`
    FOREIGN KEY (`Profile_position_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_3`
    FOREIGN KEY (`Profile_domain_id_ref`)
    REFERENCES `Archive`.`domain_organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_career_profile_person1`
    FOREIGN KEY (`person_PERSON_ID`)
    REFERENCES `Archive`.`person` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`furniture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`furniture` ;

CREATE TABLE IF NOT EXISTS `Archive`.`furniture` (
  `idfurniture` INT NOT NULL AUTO_INCREMENT,
  `furniture_org_ref` INT NULL,
  `furniture_name` VARCHAR(255) NULL,
  `furniture_code` VARCHAR(45) NULL,
  `furniture_count` INT NULL,
  `furniture_serial` VARCHAR(45) NULL,
  `furniture_note` VARCHAR(45) NULL,
  `furniture_source` INT NULL,
  `furniture_invoice_ref` INT NULL,
  `furniture_availability` ENUM('available', 'in_use', 'maintenance', 'damaged', 'retired') NULL DEFAULT 'available',
  `furniture_assigned_to_component` INT NULL,
  `furniture_assigned_to_profile` INT NULL,
  `position_store_ref` INT NULL,
  PRIMARY KEY (`idfurniture`),
  INDEX `fk_furniture_1_idx` (`furniture_org_ref` ASC) VISIBLE,
  INDEX `fk_furniture_3_idx` (`furniture_source` ASC) VISIBLE,
  INDEX `fk_furniture_4_idx` (`furniture_invoice_ref` ASC) VISIBLE,
  INDEX `fk_furniture_5_idx` (`furniture_assigned_to_component` ASC) VISIBLE,
  INDEX `fk_furniture_6_idx` (`furniture_assigned_to_profile` ASC) VISIBLE,
  INDEX `fk_furniture_store1_idx` (`position_store_ref` ASC) VISIBLE,
  CONSTRAINT `fk_furniture_1`
    FOREIGN KEY (`furniture_org_ref`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_furniture_3`
    FOREIGN KEY (`furniture_source`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_furniture_4`
    FOREIGN KEY (`furniture_invoice_ref`)
    REFERENCES `Archive`.`invoice` (`id_invoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_furniture_5`
    FOREIGN KEY (`furniture_assigned_to_component`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_furniture_6`
    FOREIGN KEY (`furniture_assigned_to_profile`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_furniture_store1`
    FOREIGN KEY (`position_store_ref`)
    REFERENCES `Archive`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`cob`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`cob` ;

CREATE TABLE IF NOT EXISTS `Archive`.`cob` (
  `idCob` INT NOT NULL AUTO_INCREMENT,
  `Cob_ref_fr` VARCHAR(45) NULL,
  `Cob_ref_ar` VARCHAR(45) NULL,
  `bay_ref_id` INT NULL,
  `cob_furniture_ref` INT NULL,
  PRIMARY KEY (`idCob`),
  INDEX `fk_Cob_1_idx` (`bay_ref_id` ASC) VISIBLE,
  INDEX `fk_cob_furniture1_idx` (`cob_furniture_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Cob_1`
    FOREIGN KEY (`bay_ref_id`)
    REFERENCES `Archive`.`bay` (`idBay`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cob_furniture1`
    FOREIGN KEY (`cob_furniture_ref`)
    REFERENCES `Archive`.`furniture` (`idfurniture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`cabinet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`cabinet` ;

CREATE TABLE IF NOT EXISTS `Archive`.`cabinet` (
  `idCabinet` INT NOT NULL AUTO_INCREMENT,
  `Cabinet_store_ref_id` INT NULL,
  `Cabinet_ref_ar` VARCHAR(45) NULL,
  `Cabinet_ref_fr` VARCHAR(45) NULL,
  `cabinetcol` VARCHAR(45) NULL,
  `cabinet_furniture_ref` INT NULL,
  PRIMARY KEY (`idCabinet`),
  INDEX `fk_Cabinet_1_idx` (`Cabinet_store_ref_id` ASC) VISIBLE,
  INDEX `fk_cabinet_furniture1_idx` (`cabinet_furniture_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Cabinet_1`
    FOREIGN KEY (`Cabinet_store_ref_id`)
    REFERENCES `Archive`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cabinet_furniture1`
    FOREIGN KEY (`cabinet_furniture_ref`)
    REFERENCES `Archive`.`furniture` (`idfurniture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`shelf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`shelf` ;

CREATE TABLE IF NOT EXISTS `Archive`.`shelf` (
  `idShelf` INT NOT NULL AUTO_INCREMENT,
  `Shelf_ref_fr` VARCHAR(45) NULL,
  `Shelf_ref_ar` VARCHAR(45) NULL,
  `cob_ref_id` INT NULL,
  `cabinet_ref_id` INT NULL,
  PRIMARY KEY (`idShelf`),
  INDEX `fk_Shelf_1_idx` (`cob_ref_id` ASC) VISIBLE,
  INDEX `fk_shelf_cabinet1_idx` (`cabinet_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Shelf_1`
    FOREIGN KEY (`cob_ref_id`)
    REFERENCES `Archive`.`cob` (`idCob`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shelf_cabinet1`
    FOREIGN KEY (`cabinet_ref_id`)
    REFERENCES `Archive`.`cabinet` (`idCabinet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`container_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`container_position` ;

CREATE TABLE IF NOT EXISTS `Archive`.`container_position` (
  `idContainer_position` INT NOT NULL AUTO_INCREMENT,
  `Container_position_shelf_ref_id` INT NULL,
  `container_position_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `slot_number` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idContainer_position`),
  INDEX `fk_Container_position_1_idx` (`Container_position_shelf_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Container_position_1`
    FOREIGN KEY (`Container_position_shelf_ref_id`)
    REFERENCES `Archive`.`shelf` (`idShelf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`app_user` ;

CREATE TABLE IF NOT EXISTS `Archive`.`app_user` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NULL,
  `USER_PASSWORD` VARCHAR(255) NULL,
  `Person_ID` INT NULL,
  `admin_privilege` TINYINT NULL,
  PRIMARY KEY (`USER_ID`),
  INDEX `fk_User_Person_idx` (`Person_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Person`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Archive`.`person` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`container`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`container` ;

CREATE TABLE IF NOT EXISTS `Archive`.`container` (
  `idContainer` INT NOT NULL AUTO_INCREMENT,
  `container_code` VARCHAR(100) NULL,
  `type_container` ENUM('box', 'folder', 'drawer', 'shelf', 'cabinet', 'digital', 'archive') NULL DEFAULT 'box',
  `container_state` ENUM('OPEN', 'CLOSED', 'PROCESSING', 'ELIMINATED') NULL DEFAULT 'OPEN',
  `container_position` INT NULL,
  `container_org` INT NULL,
  `container_added_by` INT NULL,
  `container_year` INT NULL,
  PRIMARY KEY (`idContainer`),
  INDEX `fk_container_position_ref_idx` (`container_position` ASC) VISIBLE,
  INDEX `fk_container_org_ref_idx` (`container_org` ASC) VISIBLE,
  INDEX `fk_container_app_user1_idx` (`container_added_by` ASC) VISIBLE,
  CONSTRAINT `fk_container_position_ref`
    FOREIGN KEY (`container_position`)
    REFERENCES `Archive`.`container_position` (`idContainer_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container_org_ref`
    FOREIGN KEY (`container_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container_app_user1`
    FOREIGN KEY (`container_added_by`)
    REFERENCES `Archive`.`app_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`document_type` ;

CREATE TABLE IF NOT EXISTS `Archive`.`document_type` (
  `idDocument_type` INT NOT NULL AUTO_INCREMENT,
  `document_type_label_fr` VARCHAR(255) NULL,
  `document_type_label_ar` VARCHAR(255) NULL,
  `document_type_max_age` INT NULL,
  `document_type_final_org` INT NULL,
  `document_type_domain` INT NULL,
  `document_type_code` VARCHAR(50) NULL,
  PRIMARY KEY (`idDocument_type`),
  INDEX `fk_doc_type_final_org_idx` (`document_type_final_org` ASC) VISIBLE,
  INDEX `fk_doc_type_domain_idx` (`document_type_domain` ASC) VISIBLE,
  CONSTRAINT `fk_doc_type_final_org`
    FOREIGN KEY (`document_type_final_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doc_type_domain`
    FOREIGN KEY (`document_type_domain`)
    REFERENCES `Archive`.`domain_organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`document` ;

CREATE TABLE IF NOT EXISTS `Archive`.`document` (
  `Doc_ID` INT NOT NULL AUTO_INCREMENT,
  `Doc_Label` VARCHAR(255) NULL,
  `Doc_size` BIGINT NULL,
  `document_data` BLOB NULL,
  `USER_ID` INT NULL,
  `container_ref_id` INT NULL,
  `added_by_user_id_ref` INT NULL,
  `document_url` VARCHAR(255) NULL,
  `document_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `document_last_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `reference_year` INT NULL,
  `reference_ar` VARCHAR(45) NULL,
  `reference_fr` VARCHAR(45) NULL,
  `doc_ref_org` INT NULL,
  `document_type_ref` INT NULL,
  `document_state` ENUM('MAIL', 'ISSUED', 'ACTIVE', 'ARCHIVED', 'ELIMINATED') NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`Doc_ID`),
  INDEX `fk_Document_User1_idx` (`container_ref_id` ASC) VISIBLE,
  INDEX `fk_Document_1_idx` (`added_by_user_id_ref` ASC) VISIBLE,
  UNIQUE INDEX `Doc_ID_UNIQUE` (`Doc_ID` ASC) VISIBLE,
  INDEX `fk_doc_org_idx` (`doc_ref_org` ASC) VISIBLE,
  INDEX `fk_doc_type_idx` (`document_type_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Document_User1`
    FOREIGN KEY (`container_ref_id`)
    REFERENCES `Archive`.`container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_1`
    FOREIGN KEY (`added_by_user_id_ref`)
    REFERENCES `Archive`.`app_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doc_org`
    FOREIGN KEY (`doc_ref_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doc_type`
    FOREIGN KEY (`document_type_ref`)
    REFERENCES `Archive`.`document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`transcript` ;

CREATE TABLE IF NOT EXISTS `Archive`.`transcript` (
  `idTranscript` INT NOT NULL AUTO_INCREMENT,
  `reference_transcript` VARCHAR(45) NULL,
  `sign_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `transcript_url` VARCHAR(255) NULL,
  `transcript_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTranscript`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`contained_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`contained_types` ;

CREATE TABLE IF NOT EXISTS `Archive`.`contained_types` (
  `idContained_types` INT NOT NULL AUTO_INCREMENT,
  `container_type_ref_id` INT NULL,
  `types_contained_ref_id` INT NULL,
  `contained_count` INT NULL,
  `contained_types_designation_ar` VARCHAR(255) NULL,
  `contained_types_designation_fr` VARCHAR(255) NULL,
  `contained_types_year` INT NULL,
  PRIMARY KEY (`idContained_types`),
  INDEX `fk_Contained_types_1_idx` (`container_type_ref_id` ASC) VISIBLE,
  INDEX `fk_Contained_types_2_idx` (`types_contained_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Contained_types_1`
    FOREIGN KEY (`container_type_ref_id`)
    REFERENCES `Archive`.`container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contained_types_2`
    FOREIGN KEY (`types_contained_ref_id`)
    REFERENCES `Archive`.`document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`elimination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`elimination` ;

CREATE TABLE IF NOT EXISTS `Archive`.`elimination` (
  `idElimination` INT NOT NULL AUTO_INCREMENT,
  `max_eliminated_date` DATE NULL,
  `min_eliminated_date` DATE NULL,
  `id_transcript` INT NULL,
  `doc_type_ref` INT NULL,
  `contained_types_targeted` INT NULL,
  PRIMARY KEY (`idElimination`),
  INDEX `fk_Elimination_1_idx` (`doc_type_ref` ASC) VISIBLE,
  INDEX `fk_elimination_contained_types1_idx` (`contained_types_targeted` ASC) VISIBLE,
  CONSTRAINT `id_ref_transcript`
    FOREIGN KEY (`id_transcript`)
    REFERENCES `Archive`.`transcript` (`idTranscript`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elimination_1`
    FOREIGN KEY (`doc_type_ref`)
    REFERENCES `Archive`.`document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elimination_contained_types1`
    FOREIGN KEY (`contained_types_targeted`)
    REFERENCES `Archive`.`contained_types` (`idContained_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`communication_demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`communication_demand` ;

CREATE TABLE IF NOT EXISTS `Archive`.`communication_demand` (
  `idCommunication_demand` INT NOT NULL AUTO_INCREMENT,
  `Communication_demanding_org_ref_id` INT NULL,
  `communication_demand_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `communication_demand_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCommunication_demand`),
  INDEX `fk_Communication_demand_1_idx` (`Communication_demanding_org_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Communication_demand_1`
    FOREIGN KEY (`Communication_demanding_org_ref_id`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`transfer` ;

CREATE TABLE IF NOT EXISTS `Archive`.`transfer` (
  `idTransfer` INT NOT NULL AUTO_INCREMENT,
  `source_organisation_id_ref` INT NULL,
  `destination_organisation_id_ref` INT NULL,
  `container_ref_id` INT NULL,
  `transfer_created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `transfer_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTransfer`),
  INDEX `fk_Transfer_1_idx` (`source_organisation_id_ref` ASC) VISIBLE,
  INDEX `fk_Transfer_2_idx` (`destination_organisation_id_ref` ASC) VISIBLE,
  INDEX `fk_Transfer_3_idx` (`container_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transfer_1`
    FOREIGN KEY (`source_organisation_id_ref`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transfer_2`
    FOREIGN KEY (`destination_organisation_id_ref`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transfer_3`
    FOREIGN KEY (`container_ref_id`)
    REFERENCES `Archive`.`container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`session` ;

CREATE TABLE IF NOT EXISTS `Archive`.`session` (
  `idsession` INT NOT NULL AUTO_INCREMENT,
  `session_start_date` DATE NULL,
  `session_end_date` DATE NULL,
  PRIMARY KEY (`idsession`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`trainee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`trainee` ;

CREATE TABLE IF NOT EXISTS `Archive`.`trainee` (
  `id_trainee` INT NOT NULL AUTO_INCREMENT,
  `profile_ref_id` INT NULL,
  `session_ref_id` INT NULL,
  `trainee_mark` VARCHAR(45) NULL,
  `trainee_evaluation` VARCHAR(45) NULL,
  `trainee_creation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `trainee_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_trainee`),
  INDEX `fk_trainee_1_idx` (`profile_ref_id` ASC) VISIBLE,
  INDEX `fk_trainee_2_idx` (`session_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainee_1`
    FOREIGN KEY (`profile_ref_id`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainee_2`
    FOREIGN KEY (`session_ref_id`)
    REFERENCES `Archive`.`session` (`idsession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`communication_response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`communication_response` ;

CREATE TABLE IF NOT EXISTS `Archive`.`communication_response` (
  `idCommunication_response` INT NOT NULL AUTO_INCREMENT,
  `Communication_demand_ref_id` INT NOT NULL,
  `communication_response_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `communication_response_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `communication_response_status` ENUM('PENDING', 'REJECTED', 'ACCEPTED', 'DELIVERED', 'RETURNED') NULL DEFAULT 'PENDING',
  `opinion_given_by` INT NULL,
  PRIMARY KEY (`idCommunication_response`),
  INDEX `fk_Communication_response_1_idx` (`Communication_demand_ref_id` ASC) VISIBLE,
  INDEX `fk_communication_response_career_profile1_idx` (`opinion_given_by` ASC) VISIBLE,
  CONSTRAINT `fk_Communication_response_1`
    FOREIGN KEY (`Communication_demand_ref_id`)
    REFERENCES `Archive`.`communication_demand` (`idCommunication_demand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_communication_response_career_profile1`
    FOREIGN KEY (`opinion_given_by`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`communication_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`communication_subject` ;

CREATE TABLE IF NOT EXISTS `Archive`.`communication_subject` (
  `Communicated_doc_ref_id` INT NULL,
  `subject_source_org` INT NOT NULL,
  `Communication_response_ref_id` INT NOT NULL,
  `subject _reference` VARCHAR(255) NULL,
  `subject_description` VARCHAR(255) NULL,
  INDEX `fk_Communication_subject_1_idx` (`Communication_response_ref_id` ASC) VISIBLE,
  INDEX `fk_Communication_subject_2_idx` (`Communicated_doc_ref_id` ASC) VISIBLE,
  INDEX `fk_communication_subject_organisation1_idx` (`subject_source_org` ASC) VISIBLE,
  CONSTRAINT `fk_Communication_subject_1`
    FOREIGN KEY (`Communication_response_ref_id`)
    REFERENCES `Archive`.`communication_response` (`idCommunication_response`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Communication_subject_2`
    FOREIGN KEY (`Communicated_doc_ref_id`)
    REFERENCES `Archive`.`document` (`Doc_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_communication_subject_organisation1`
    FOREIGN KEY (`subject_source_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`transferred_contained_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`transferred_contained_types` ;

CREATE TABLE IF NOT EXISTS `Archive`.`transferred_contained_types` (
  `idtransferred_contained_types` INT NOT NULL AUTO_INCREMENT,
  `transferred_contained_types_id_ref` INT NULL,
  `transferred_types_contained` INT NULL,
  `transferred_contained_types_checked_by` INT NULL,
  INDEX `fk_transferred_contained_types_1_idx` (`transferred_types_contained` ASC) VISIBLE,
  INDEX `fk_transferred_contained_types_2_idx` (`transferred_contained_types_id_ref` ASC) VISIBLE,
  PRIMARY KEY (`idtransferred_contained_types`),
  INDEX `fk_transferred_contained_types_3_idx` (`transferred_contained_types_checked_by` ASC) VISIBLE,
  CONSTRAINT `fk_transferred_contained_types_1`
    FOREIGN KEY (`transferred_types_contained`)
    REFERENCES `Archive`.`contained_types` (`idContained_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferred_contained_types_2`
    FOREIGN KEY (`transferred_contained_types_id_ref`)
    REFERENCES `Archive`.`transfer` (`idTransfer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferred_contained_types_3`
    FOREIGN KEY (`transferred_contained_types_checked_by`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`inspection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`inspection` ;

CREATE TABLE IF NOT EXISTS `Archive`.`inspection` (
  `id_inspection` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL,
  `inspection_transcript` LONGTEXT NULL,
  `insp_org_ref` INT NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`id_inspection`),
  INDEX `fk_Inspection_1_idx` (`insp_org_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Inspection_1`
    FOREIGN KEY (`insp_org_ref`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`review` ;

CREATE TABLE IF NOT EXISTS `Archive`.`review` (
  `id_review` INT NOT NULL AUTO_INCREMENT,
  `review_type` VARCHAR(45) NULL,
  `review_reference` VARCHAR(45) NULL,
  `org_ref` INT NULL,
  `reviewed_year` INT NULL,
  `treated_archive_boxes` INT NULL,
  `inventoried_archive_boxes` INT NULL,
  `reviewed_year_note` VARCHAR(45) NULL,
  PRIMARY KEY (`id_review`),
  INDEX `fk_review_1_idx` (`org_ref` ASC) VISIBLE,
  CONSTRAINT `fk_review_1`
    FOREIGN KEY (`org_ref`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `Archive`.`vehicle` (
  `id_vehicle` INT NOT NULL AUTO_INCREMENT,
  `vehicle_serial` VARCHAR(255) NULL,
  `chassis_number` VARCHAR(45) NULL,
  `vehicle_name` VARCHAR(255) NULL,
  `org_ref` INT NULL,
  `vehicle_invoice_ref` INT NULL,
  `vehicle_state` ENUM('operational', 'maintenance', 'repair', 'retired', 'accident') NULL DEFAULT 'operational',
  PRIMARY KEY (`id_vehicle`),
  INDEX `fk_vehicle_1_idx` (`org_ref` ASC) VISIBLE,
  INDEX `fk_vehicle_3_idx` (`vehicle_invoice_ref` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_1`
    FOREIGN KEY (`org_ref`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_3`
    FOREIGN KEY (`vehicle_invoice_ref`)
    REFERENCES `Archive`.`invoice` (`id_invoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`component_community`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`component_community` ;

CREATE TABLE IF NOT EXISTS `Archive`.`component_community` (
  `id_component_membership` INT NOT NULL AUTO_INCREMENT,
  `component_member_id` INT NULL,
  `component_member_in` INT NULL,
  `component_membership_activity` VARCHAR(45) NULL,
  `component_community_title_ar` VARCHAR(255) NULL,
  `component_community_title_fr` VARCHAR(255) NULL,
  PRIMARY KEY (`id_component_membership`),
  INDEX `fk_component_community_1_idx` (`component_member_id` ASC) VISIBLE,
  INDEX `fk_component_community_2_idx` (`component_member_in` ASC) VISIBLE,
  CONSTRAINT `fk_component_community_1`
    FOREIGN KEY (`component_member_id`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_community_2`
    FOREIGN KEY (`component_member_in`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`storable_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`storable_item` ;

CREATE TABLE IF NOT EXISTS `Archive`.`storable_item` (
  `id_storable_item` INT NOT NULL AUTO_INCREMENT,
  `storable_item_position` INT NULL,
  `storable_item_quantity` VARCHAR(45) NULL,
  `storable_item_last_updated` DATETIME NULL,
  `storable_item_invoice_ref` INT NULL,
  `storable_item_availability` ENUM('in_stock', 'reserved', 'issued', 'damaged', 'lost') NULL DEFAULT 'in_stock',
  `storable_item_store_ref` INT NULL,
  `storable_item_designation` VARCHAR(100) NULL,
  `storable_item_code` VARCHAR(45) NULL,
  `storable_item_org` INT NULL,
  `storable_item_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id_storable_item`),
  INDEX `fk_storable_item_1_idx` (`storable_item_position` ASC) VISIBLE,
  INDEX `fk_storable_item_2_idx` (`storable_item_invoice_ref` ASC) VISIBLE,
  INDEX `fk_storable_item_3_idx` (`storable_item_store_ref` ASC) VISIBLE,
  INDEX `fk_storable_item_4_idx` (`storable_item_org` ASC) VISIBLE,
  CONSTRAINT `fk_storable_item_1`
    FOREIGN KEY (`storable_item_position`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storable_item_2`
    FOREIGN KEY (`storable_item_invoice_ref`)
    REFERENCES `Archive`.`invoice` (`id_invoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storable_item_3`
    FOREIGN KEY (`storable_item_store_ref`)
    REFERENCES `Archive`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storable_item_4`
    FOREIGN KEY (`storable_item_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`provision_demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`provision_demand` ;

CREATE TABLE IF NOT EXISTS `Archive`.`provision_demand` (
  `id_provision_demand` INT NOT NULL AUTO_INCREMENT,
  `provision_demand_issuer` INT NULL,
  `provision_demand_destination` INT NULL,
  `provision_demand_item` INT NULL,
  `provision_demand_quantity` VARCHAR(45) NULL,
  `provision_demand_created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `provision_demand_state` ENUM('PENDING', 'DELAYED', 'REJECTED', 'APPROVED', 'DELIVERED') NULL,
  `provision_demand_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_provision_demand`),
  INDEX `fk_provision_demand_1_idx` (`provision_demand_issuer` ASC) VISIBLE,
  INDEX `fk_provision_demand_2_idx` (`provision_demand_destination` ASC) VISIBLE,
  INDEX `fk_provision_demand_3_idx` (`provision_demand_item` ASC) VISIBLE,
  CONSTRAINT `fk_provision_demand_1`
    FOREIGN KEY (`provision_demand_issuer`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provision_demand_2`
    FOREIGN KEY (`provision_demand_destination`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provision_demand_3`
    FOREIGN KEY (`provision_demand_item`)
    REFERENCES `Archive`.`storable_item` (`id_storable_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`visitor` ;

CREATE TABLE IF NOT EXISTS `Archive`.`visitor` (
  `id_visitor` INT NOT NULL AUTO_INCREMENT,
  `visitor_as_person` INT NULL,
  `visitor_purpose` VARCHAR(255) NULL,
  `visitor_entry` DATETIME NULL,
  `visitor_leave` DATETIME NULL,
  PRIMARY KEY (`id_visitor`),
  INDEX `fk_visitor_1_idx` (`visitor_as_person` ASC) VISIBLE,
  CONSTRAINT `fk_visitor_1`
    FOREIGN KEY (`visitor_as_person`)
    REFERENCES `Archive`.`person` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`course` ;

CREATE TABLE IF NOT EXISTS `Archive`.`course` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `course_title_ar` VARCHAR(255) NULL,
  `course_title_fr` VARCHAR(255) NULL,
  `course_title_en` VARCHAR(255) NULL,
  `course_start` DATETIME NULL,
  `course_end` DATETIME NULL,
  `course_org` INT NULL,
  PRIMARY KEY (`id_course`),
  INDEX `fk_course_org_idx` (`course_org` ASC) VISIBLE,
  CONSTRAINT `fk_course_org`
    FOREIGN KEY (`course_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`security_shift_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`security_shift_position` ;

CREATE TABLE IF NOT EXISTS `Archive`.`security_shift_position` (
  `id_shift_position` INT NOT NULL AUTO_INCREMENT,
  `shift_position_title_ar` VARCHAR(45) NULL,
  `shift_position_title_fr` VARCHAR(45) NULL,
  `shift_position_title_en` VARCHAR(45) NULL,
  `security_shift_details_ar` TEXT NULL,
  `security_shift_details_fr` TEXT NULL,
  `security_shift_details_en` TEXT NULL,
  PRIMARY KEY (`id_shift_position`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`security_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`security_shift` ;

CREATE TABLE IF NOT EXISTS `Archive`.`security_shift` (
  `id_security_shift` INT NOT NULL AUTO_INCREMENT,
  `shift_position_ref` INT NULL,
  `security_shift_at` INT NULL,
  `security_shift_who` INT NULL,
  `security_shift_what` INT NULL,
  `security_shift_start` DATETIME NULL,
  `security_shift_end` DATETIME NULL,
  `security_shift_responsible` INT NULL,
  `security_shift_approved` TINYINT NULL,
  `security_shift_state` ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'missed') NULL DEFAULT 'scheduled',
  `security_shift_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `security_shift_last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_security_shift`),
  INDEX `fk_security_shift_1_idx` (`security_shift_at` ASC) VISIBLE,
  INDEX `fk_security_shift_3_idx` (`security_shift_what` ASC) VISIBLE,
  INDEX `fk_security_shift_4_idx` (`shift_position_ref` ASC) VISIBLE,
  INDEX `fk_security_shift_5_idx` (`security_shift_responsible` ASC) VISIBLE,
  INDEX `fk_security_shift_2_idx` (`security_shift_who` ASC) VISIBLE,
  CONSTRAINT `fk_security_shift_1`
    FOREIGN KEY (`security_shift_at`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_security_shift_2`
    FOREIGN KEY (`security_shift_who`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_security_shift_3`
    FOREIGN KEY (`security_shift_what`)
    REFERENCES `Archive`.`storable_item` (`id_storable_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_security_shift_4`
    FOREIGN KEY (`shift_position_ref`)
    REFERENCES `Archive`.`security_shift_position` (`id_shift_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_security_shift_5`
    FOREIGN KEY (`security_shift_responsible`)
    REFERENCES `Archive`.`app_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`role` ;

CREATE TABLE IF NOT EXISTS `Archive`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NULL,
  `role_description` VARCHAR(255) NULL,
  `role_name_ar` VARCHAR(100) NULL,
  `role_description_ar` VARCHAR(255) NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`permission` ;

CREATE TABLE IF NOT EXISTS `Archive`.`permission` (
  `id_permission` INT NOT NULL AUTO_INCREMENT,
  `permission_key` VARCHAR(100) NULL,
  `permission_description` VARCHAR(255) NULL,
  `permission_description_ar` VARCHAR(255) NULL,
  PRIMARY KEY (`id_permission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`user_role` ;

CREATE TABLE IF NOT EXISTS `Archive`.`user_role` (
  `user_role` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_role`, `role_id`),
  INDEX `fk_user_role_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_role`)
    REFERENCES `Archive`.`app_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `Archive`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `Archive`.`role_permission` (
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  `scope` ENUM('GLOBAL', 'ORGANISATION', 'DOMAIN', 'SECTOR', 'REGION', 'COURSE', 'SESSION', 'CONTAINER', 'COMPONENT', 'STORE', 'BAY', 'ACTIVITY', 'TRANSFER', 'BUDGET', 'PARAGRAPH') NULL,
  `scope_ref` INT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `fk_role_permission_role_permission_idx` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_permission_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `Archive`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permission_role_permission`
    FOREIGN KEY (`permission_id`)
    REFERENCES `Archive`.`permission` (`id_permission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`audit_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`audit_log` ;

CREATE TABLE IF NOT EXISTS `Archive`.`audit_log` (
  `id_audit` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `action` VARCHAR(50) NULL,
  `table_name` VARCHAR(100) NULL,
  `record_id` INT NULL,
  `old_value` JSON NULL,
  `new_value` JSON NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_audit`),
  INDEX `fk_audit_log_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_audit_log_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Archive`.`app_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`layout_element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`layout_element` ;

CREATE TABLE IF NOT EXISTS `Archive`.`layout_element` (
  `id_layout_element` INT NOT NULL AUTO_INCREMENT,
  `layout_id` INT NULL,
  `element_type` VARCHAR(50) NULL,
  `element_ref_id` INT NULL,
  `layout_project_name` VARCHAR(255) NOT NULL,
  `x` FLOAT NULL,
  `y` FLOAT NULL,
  `width` FLOAT NULL,
  `height` FLOAT NULL,
  `reference` ENUM('ABSOLUTE', 'RELATIVE') NULL DEFAULT 'ABSOLUTE',
  PRIMARY KEY (`id_layout_element`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`store_layout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`store_layout` ;

CREATE TABLE IF NOT EXISTS `Archive`.`store_layout` (
  `id_store_layout` INT NOT NULL AUTO_INCREMENT,
  `layout_image_url` VARCHAR(255) NULL,
  `width` INT NULL,
  `height` INT NULL,
  `layout_image_blob` BLOB NULL,
  PRIMARY KEY (`id_store_layout`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`evaluation` ;

CREATE TABLE IF NOT EXISTS `Archive`.`evaluation` (
  `evaluation_id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NULL,
  `evaluation_type` ENUM('exam', 'quiz', 'assessment') NULL,
  PRIMARY KEY (`evaluation_id`),
  INDEX `fk_evaluation_course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_evaluation_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `Archive`.`course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`evaluation_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`evaluation_result` ;

CREATE TABLE IF NOT EXISTS `Archive`.`evaluation_result` (
  `id_result` INT NOT NULL AUTO_INCREMENT,
  `evaluation_id` INT NULL,
  `trainee_id` INT NULL,
  `score` FLOAT NULL,
  `graded_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id_result`),
  INDEX `fk_result_evaluation_idx` (`evaluation_id` ASC) VISIBLE,
  INDEX `fk_result_trainee_idx` (`trainee_id` ASC) VISIBLE,
  CONSTRAINT `fk_result_evaluation`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `Archive`.`evaluation` (`evaluation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_trainee`
    FOREIGN KEY (`trainee_id`)
    REFERENCES `Archive`.`trainee` (`id_trainee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`course_trainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`course_trainer` ;

CREATE TABLE IF NOT EXISTS `Archive`.`course_trainer` (
  `id_course` INT NOT NULL,
  `id_career_profile_trainer` INT NOT NULL,
  PRIMARY KEY (`id_course`, `id_career_profile_trainer`),
  INDEX `fk_trainer_profile_idx` (`id_career_profile_trainer` ASC) VISIBLE,
  CONSTRAINT `fk_trainer_course`
    FOREIGN KEY (`id_course`)
    REFERENCES `Archive`.`course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_profile`
    FOREIGN KEY (`id_career_profile_trainer`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`activity` ;

CREATE TABLE IF NOT EXISTS `Archive`.`activity` (
  `id_activity` INT NOT NULL AUTO_INCREMENT,
  `activity_type` ENUM('MISSION', 'LEAVE', 'DAY_OFF', 'SICK_LEAVE', 'TRAINING', 'ASSIGNMENT', 'PUNISHMENT', 'SUSPENSION', 'MAINTENANCE', 'OTHER') NULL DEFAULT 'OTHER',
  `start_date` DATETIME NULL DEFAULT NOW(),
  `end_date` DATETIME NULL DEFAULT NOW(),
  `activity_status` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `career_profile_id` INT NULL,
  `notes` JSON NULL,
  PRIMARY KEY (`id_activity`),
  INDEX `fk_activity_profile_idx` (`career_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_activity_profile`
    FOREIGN KEY (`career_profile_id`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`inspection_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`inspection_assignment` ;

CREATE TABLE IF NOT EXISTS `Archive`.`inspection_assignment` (
  `id_inspection_assignment` INT NOT NULL AUTO_INCREMENT,
  `inspection_id` INT NULL,
  `assigned_profile` INT NULL,
  `assigned_role` ENUM('LEAD', 'MEMBER', 'DRIVER') NULL,
  PRIMARY KEY (`id_inspection_assignment`),
  INDEX `fk_inspection_idx` (`inspection_id` ASC) VISIBLE,
  INDEX `fk_person_idx` (`assigned_profile` ASC) VISIBLE,
  CONSTRAINT `fk_inspection`
    FOREIGN KEY (`inspection_id`)
    REFERENCES `Archive`.`inspection` (`id_inspection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person`
    FOREIGN KEY (`assigned_profile`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`assignment_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`assignment_activity` ;

CREATE TABLE IF NOT EXISTS `Archive`.`assignment_activity` (
  `id_inspection_assignment` INT NOT NULL,
  `id_activity` INT NOT NULL,
  PRIMARY KEY (`id_inspection_assignment`, `id_activity`),
  INDEX `fk_assigned_activity_idx` (`id_activity` ASC) VISIBLE,
  CONSTRAINT `fk_assigned_activity`
    FOREIGN KEY (`id_activity`)
    REFERENCES `Archive`.`activity` (`id_activity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assigned_inspection`
    FOREIGN KEY (`id_inspection_assignment`)
    REFERENCES `Archive`.`inspection_assignment` (`id_inspection_assignment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`treatment` ;

CREATE TABLE IF NOT EXISTS `Archive`.`treatment` (
  `id_treatment` INT NOT NULL,
  `treatment_profile` INT NULL,
  `treatment_container` INT NULL,
  `treatment_type` ENUM('CLASSIFICATION', 'INDEXING', 'DIGITIZATION', 'TRANSFER', 'APPRAISAL', 'VALIDATION', 'ACCESS_REQUEST', 'LOAN', 'RETURN', 'RESTORATION', 'REPRODUCTION', 'PRESERVATION', 'MIGRATION') NULL,
  PRIMARY KEY (`id_treatment`),
  INDEX `fk_treatment_profile_idx` (`treatment_profile` ASC) VISIBLE,
  INDEX `fk_treatment_container_idx` (`treatment_container` ASC) VISIBLE,
  CONSTRAINT `fk_treatment_profile`
    FOREIGN KEY (`treatment_profile`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_treatment_container`
    FOREIGN KEY (`treatment_container`)
    REFERENCES `Archive`.`container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`equipment` ;

CREATE TABLE IF NOT EXISTS `Archive`.`equipment` (
  `id_equipment` INT NOT NULL AUTO_INCREMENT,
  `equipment_name_ar` VARCHAR(255) NULL,
  `equipment_name_fr` VARCHAR(255) NULL,
  `category` VARCHAR(45) NULL,
  `brand` VARCHAR(255) NULL,
  `model` VARCHAR(255) NULL,
  `serial_number` VARCHAR(255) NULL,
  `equipment_status` ENUM('AVAILABLE', 'IN_USE', 'IN_MAINTENANCE', 'BROKEN', 'LOST', 'DISPOSED') NULL DEFAULT 'AVAILABLE',
  `equipment_source` INT NULL,
  `equipment_org_assignment_ref` VARCHAR(255) NULL,
  `equipment_component_assignment_ref` VARCHAR(255) NULL,
  `equipment_assignment_to_component` INT NULL,
  `equipment_assignment_to_profile` INT NULL,
  `equipment_owner_org` INT NULL,
  `equipment_store_ref` INT NULL,
  PRIMARY KEY (`id_equipment`),
  INDEX `fk_equipment_to_component_idx` (`equipment_assignment_to_component` ASC) VISIBLE,
  INDEX `fk_equipment_to_org_idx` (`equipment_owner_org` ASC) VISIBLE,
  INDEX `fk_equipment_source_org_idx` (`equipment_source` ASC) VISIBLE,
  INDEX `fk_equipment_profile_idx` (`equipment_assignment_to_profile` ASC) VISIBLE,
  INDEX `fk_equipment_store_idx` (`equipment_store_ref` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_to_component`
    FOREIGN KEY (`equipment_assignment_to_component`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_to_org`
    FOREIGN KEY (`equipment_owner_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_source_org`
    FOREIGN KEY (`equipment_source`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_profile`
    FOREIGN KEY (`equipment_assignment_to_profile`)
    REFERENCES `Archive`.`career_profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_store`
    FOREIGN KEY (`equipment_store_ref`)
    REFERENCES `Archive`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`org_shift_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`org_shift_position` ;

CREATE TABLE IF NOT EXISTS `Archive`.`org_shift_position` (
  `id_organisation` INT NOT NULL,
  `id_security_shift_position` INT NOT NULL,
  PRIMARY KEY (`id_organisation`, `id_security_shift_position`),
  INDEX `fk_shift_position_idx` (`id_security_shift_position` ASC) VISIBLE,
  CONSTRAINT `fk_shift_org`
    FOREIGN KEY (`id_organisation`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shift_position`
    FOREIGN KEY (`id_security_shift_position`)
    REFERENCES `Archive`.`security_shift_position` (`id_shift_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`role_organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`role_organisation` ;

CREATE TABLE IF NOT EXISTS `Archive`.`role_organisation` (
  `id_role_organisation` INT NOT NULL AUTO_INCREMENT,
  `org_id` INT NULL,
  `role_id` INT NOT NULL,
  `component_id` INT NULL,
  PRIMARY KEY (`id_role_organisation`),
  INDEX `fk_org_id_idx` (`org_id` ASC) VISIBLE,
  INDEX `fk_role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_component_id_idx` (`component_id` ASC) VISIBLE,
  CONSTRAINT `fk_org_id`
    FOREIGN KEY (`org_id`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `Archive`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_id`
    FOREIGN KEY (`component_id`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`course_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`course_session` ;

CREATE TABLE IF NOT EXISTS `Archive`.`course_session` (
  `id_course` INT NOT NULL,
  `id_session` INT NOT NULL,
  PRIMARY KEY (`id_course`, `id_session`),
  INDEX `fk_session_idx` (`id_session` ASC) VISIBLE,
  CONSTRAINT `fk_course`
    FOREIGN KEY (`id_course`)
    REFERENCES `Archive`.`course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session`
    FOREIGN KEY (`id_session`)
    REFERENCES `Archive`.`session` (`idsession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`demand_approval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`demand_approval` ;

CREATE TABLE IF NOT EXISTS `Archive`.`demand_approval` (
  `demand_approval_value` TINYINT NULL,
  `demand_approval_component` INT NOT NULL,
  `demand_approval_user` INT NULL,
  `demand_ref` INT NOT NULL,
  `demand_approval_org` INT NULL,
  `demand_approval_comment` VARCHAR(255) NULL,
  PRIMARY KEY (`demand_approval_component`, `demand_ref`),
  INDEX `fk_demand_idx` (`demand_ref` ASC) VISIBLE,
  INDEX `fk_user_idx` (`demand_approval_user` ASC) VISIBLE,
  INDEX `fk_approval_org_idx` (`demand_approval_org` ASC) VISIBLE,
  CONSTRAINT `fk_demand`
    FOREIGN KEY (`demand_ref`)
    REFERENCES `Archive`.`provision_demand` (`id_provision_demand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component`
    FOREIGN KEY (`demand_approval_component`)
    REFERENCES `Archive`.`component` (`id_component`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`demand_approval_user`)
    REFERENCES `Archive`.`app_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approval_org`
    FOREIGN KEY (`demand_approval_org`)
    REFERENCES `Archive`.`organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`container_fusion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`container_fusion` ;

CREATE TABLE IF NOT EXISTS `Archive`.`container_fusion` (
  `destination_container_id` INT NOT NULL,
  `source_container_id` INT NOT NULL,
  `fusion_person_id` INT NULL,
  `container_fusion_at` DATE NULL,
  INDEX `fk_container_fusion_container1_idx` (`source_container_id` ASC) VISIBLE,
  INDEX `fk_container_fusion_container2_idx` (`destination_container_id` ASC) VISIBLE,
  INDEX `fk_container_fusion_person1_idx` (`fusion_person_id` ASC) VISIBLE,
  CONSTRAINT `fk_container_fusion_container1`
    FOREIGN KEY (`source_container_id`)
    REFERENCES `Archive`.`container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container_fusion_container2`
    FOREIGN KEY (`destination_container_id`)
    REFERENCES `Archive`.`container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_container_fusion_person1`
    FOREIGN KEY (`fusion_person_id`)
    REFERENCES `Archive`.`person` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Archive` ;

-- -----------------------------------------------------
-- procedure InsertDataIntoMultipleTables
-- -----------------------------------------------------

USE `Archive`;
DROP procedure IF EXISTS `Archive`.`InsertDataIntoMultipleTables`;

DELIMITER $$
USE `Archive`$$
CREATE PROCEDURE InsertDataIntoMultipleTables (
    IN p_name VARCHAR(255),
    IN p_email VARCHAR(255),
    IN p_address VARCHAR(255)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 'An error occurred. Transaction rolled back.';
    END;

    START TRANSACTION;

    INSERT INTO table1 (name, email) VALUES (p_name, p_email);
    SET @last_id := LAST_INSERT_ID();

    INSERT INTO table2 (user_id, address) VALUES (@last_id, p_address);

    COMMIT;

    SELECT 'Data inserted successfully.';
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetEmployeeCount
-- -----------------------------------------------------

USE `Archive`;
DROP procedure IF EXISTS `Archive`.`GetEmployeeCount`;

DELIMITER $$
USE `Archive`$$
CREATE PROCEDURE GetEmployeeCount(IN departmentId INT, OUT employeeCount INT)
BEGIN
    SELECT COUNT(*) INTO employeeCount
    FROM employees
    WHERE department_id = departmentId;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Trainee
-- -----------------------------------------------------

USE `Archive`;
DROP procedure IF EXISTS `Archive`.`Trainee`;

DELIMITER $$
USE `Archive`$$
CREATE PROCEDURE Trainee (
    IN p_name VARCHAR(255),
    IN p_email VARCHAR(255),
    IN p_address VARCHAR(255)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 'An error occurred. Transaction rolled back.';
    END;

    START TRANSACTION;

    INSERT INTO table1 (name, email) VALUES (p_name, p_email);
    SET @last_id := LAST_INSERT_ID();

    INSERT INTO table2 (user_id, address) VALUES (@last_id, p_address);

    COMMIT;

    SELECT 'Data inserted successfully.';
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
