-- MySQL Script generated by MySQL Workbench
-- Mi 10 Mai 2023 23:38:52 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema archive
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `archive` ;

-- -----------------------------------------------------
-- Schema archive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `archive` DEFAULT CHARACTER SET utf8 ;
USE `archive` ;

-- -----------------------------------------------------
-- Table `archive`.`Domain_Organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Domain_Organisation` ;

CREATE TABLE IF NOT EXISTS `archive`.`Domain_Organisation` (
  `idDomain_Organisation` INT NOT NULL AUTO_INCREMENT,
  `Domain_Organisation_label_fr` VARCHAR(45) NULL,
  `Domain_Organisation_label_ar` VARCHAR(45) NULL,
  `Domain_Organisation_acronym_fr` VARCHAR(45) NULL,
  `Domain_Organisation_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idDomain_Organisation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Sector` ;

CREATE TABLE IF NOT EXISTS `archive`.`Sector` (
  `idSector` INT NOT NULL AUTO_INCREMENT,
  `label_sector_fr` VARCHAR(45) NULL,
  `label_sector_ar` VARCHAR(45) NULL,
  `acronym_sector_fr` VARCHAR(45) NULL,
  `acronym_sector_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idSector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Organisation` ;

CREATE TABLE IF NOT EXISTS `archive`.`Organisation` (
  `id_Organisation` INT NOT NULL AUTO_INCREMENT,
  `Organisation_name_ar` VARCHAR(255) NULL,
  `Organisation_name_fr` VARCHAR(255) NULL,
  `ACRONYM_AR` VARCHAR(45) NULL,
  `ACRONYM_FR` VARCHAR(45) NULL,
  `Organisation_domain_id_ref` INT NULL,
  `sector_ref_id` INT NULL,
  PRIMARY KEY (`id_Organisation`),
  INDEX `fk_Organisation_1_idx` (`Organisation_domain_id_ref` ASC) VISIBLE,
  INDEX `fk_Organisation_2_idx` (`sector_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Organisation_1`
    FOREIGN KEY (`Organisation_domain_id_ref`)
    REFERENCES `archive`.`Domain_Organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organisation_2`
    FOREIGN KEY (`sector_ref_id`)
    REFERENCES `archive`.`Sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`doc_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`doc_reference` ;

CREATE TABLE IF NOT EXISTS `archive`.`doc_reference` (
  `reference_id` INT NOT NULL AUTO_INCREMENT,
  `reference_year` SMALLINT NULL,
  `reference_ar` VARCHAR(45) NULL,
  `reference_fr` VARCHAR(45) NULL,
  `Organisation_id_Organisation` INT NULL,
  PRIMARY KEY (`reference_id`, `Organisation_id_Organisation`),
  INDEX `fk_doc_reference_Organisation1_idx` (`Organisation_id_Organisation` ASC) VISIBLE,
  CONSTRAINT `fk_doc_reference_Organisation1`
    FOREIGN KEY (`Organisation_id_Organisation`)
    REFERENCES `archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Container`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Container` ;

CREATE TABLE IF NOT EXISTS `archive`.`Container` (
  `idContainer` INT NOT NULL AUTO_INCREMENT,
  `type_container` VARCHAR(45) NULL,
  PRIMARY KEY (`idContainer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Document` ;

CREATE TABLE IF NOT EXISTS `archive`.`Document` (
  `Doc_ID` INT NOT NULL AUTO_INCREMENT,
  `Doc_Label` VARCHAR(255) NULL,
  `Doc_size` BIGINT NULL,
  `Doc_number_of_chunks` SMALLINT NULL,
  `reference_id` INT NULL,
  `USER_ID` INT NULL,
  `Doc_chunk_number` SMALLINT NULL,
  `Documentcol` INT NULL,
  `container_ref_id` INT NULL,
  PRIMARY KEY (`Doc_ID`, `reference_id`, `USER_ID`),
  INDEX `fk_Document_User1_idx` (`container_ref_id` ASC) VISIBLE,
  INDEX `fk_Document_reference1_idx` (`reference_id` ASC) VISIBLE,
  CONSTRAINT `fk_Document_reference1`
    FOREIGN KEY (`reference_id`)
    REFERENCES `archive`.`doc_reference` (`reference_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_User1`
    FOREIGN KEY (`container_ref_id`)
    REFERENCES `archive`.`Container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`profile_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`profile_rank` ;

CREATE TABLE IF NOT EXISTS `archive`.`profile_rank` (
  `idprofile_rank` INT NOT NULL,
  `profile_rank_label_fr` VARCHAR(45) NULL,
  `profile_rank_label_ar` VARCHAR(45) NULL,
  `profile_rank_acronym_fr` VARCHAR(45) NULL,
  `profile_rank_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofile_rank`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Profile` ;

CREATE TABLE IF NOT EXISTS `archive`.`Profile` (
  `idProfile` INT NOT NULL AUTO_INCREMENT,
  `Profile_serial` VARCHAR(45) NULL,
  `Profile_rank_id_ref` INT NULL,
  `Profile_position_org` INT NULL,
  `Profile_domain_id_ref` INT NULL,
  PRIMARY KEY (`idProfile`),
  INDEX `fk_Profile_1_idx` (`Profile_rank_id_ref` ASC) VISIBLE,
  INDEX `fk_Profile_2_idx` (`Profile_position_org` ASC) VISIBLE,
  INDEX `fk_Profile_3_idx` (`Profile_domain_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_1`
    FOREIGN KEY (`Profile_rank_id_ref`)
    REFERENCES `archive`.`profile_rank` (`idprofile_rank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_2`
    FOREIGN KEY (`Profile_position_org`)
    REFERENCES `archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_3`
    FOREIGN KEY (`Profile_domain_id_ref`)
    REFERENCES `archive`.`Domain_Organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Person` ;

CREATE TABLE IF NOT EXISTS `archive`.`Person` (
  `PERSON_ID` INT NOT NULL,
  `Person_name` VARCHAR(45) NULL,
  `Person_lastname` VARCHAR(45) NULL,
  `Person_profile_id_ref` INT NULL,
  PRIMARY KEY (`PERSON_ID`),
  INDEX `fk_Person_1_idx` (`Person_profile_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Person_1`
    FOREIGN KEY (`Person_profile_id_ref`)
    REFERENCES `archive`.`Profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`User` ;

CREATE TABLE IF NOT EXISTS `archive`.`User` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` VARCHAR(45) NULL,
  `USER_PASSWORD` VARCHAR(255) NULL,
  `Person_ID` INT NULL,
  PRIMARY KEY (`USER_ID`),
  INDEX `fk_User_Person_idx` (`Person_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Person`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `archive`.`Person` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Document_chunk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Document_chunk` ;

CREATE TABLE IF NOT EXISTS `archive`.`Document_chunk` (
  `idChunk` INT NOT NULL AUTO_INCREMENT,
  `Document_Doc_ID` INT NOT NULL,
  `Document_chunk_data` BLOB NULL,
  PRIMARY KEY (`idChunk`, `Document_Doc_ID`),
  INDEX `fk_Document_chunk_Document1_idx` (`Document_Doc_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Document_chunk_Document1`
    FOREIGN KEY (`Document_Doc_ID`)
    REFERENCES `archive`.`Document` (`Doc_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Transcript` ;

CREATE TABLE IF NOT EXISTS `archive`.`Transcript` (
  `idTranscript` INT NOT NULL AUTO_INCREMENT,
  `reference_transcript` VARCHAR(45) NULL,
  PRIMARY KEY (`idTranscript`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Document_type` ;

CREATE TABLE IF NOT EXISTS `archive`.`Document_type` (
  `idDocument_type` INT NOT NULL AUTO_INCREMENT,
  `document_type_label_fr` VARCHAR(45) NULL,
  `document_type_label_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocument_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Elimination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Elimination` ;

CREATE TABLE IF NOT EXISTS `archive`.`Elimination` (
  `idElimination` INT NOT NULL AUTO_INCREMENT,
  `max_eliminated_date` DATE NULL,
  `min_eliminated_date` DATE NULL,
  `id_transcript` INT NULL,
  `doc_type_ref` INT NOT NULL,
  `elimination_container_ref_id` INT NULL,
  PRIMARY KEY (`idElimination`, `id_transcript`, `doc_type_ref`),
  INDEX `id_ref_transcript_idx` (`id_transcript` ASC, `doc_type_ref` ASC) VISIBLE,
  INDEX `fk_Elimination_1_idx` (`doc_type_ref` ASC) VISIBLE,
  INDEX `fk_Elimination_2_idx` (`elimination_container_ref_id` ASC) VISIBLE,
  CONSTRAINT `id_ref_transcript`
    FOREIGN KEY (`id_transcript` , `doc_type_ref`)
    REFERENCES `archive`.`Transcript` (`idTranscript` , `idTranscript`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elimination_1`
    FOREIGN KEY (`doc_type_ref`)
    REFERENCES `archive`.`Document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elimination_2`
    FOREIGN KEY (`elimination_container_ref_id`)
    REFERENCES `archive`.`Container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Communication_demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Communication_demand` ;

CREATE TABLE IF NOT EXISTS `archive`.`Communication_demand` (
  `idCommunication_demand` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCommunication_demand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`Transfer` ;

CREATE TABLE IF NOT EXISTS `archive`.`Transfer` (
  `idTransfer` INT NOT NULL AUTO_INCREMENT,
  `source_organisation_id_ref` INT NULL,
  `destination_organisation_id_ref` INT NULL,
  `container_ref_id` VARCHAR(45) NULL,
  PRIMARY KEY (`idTransfer`),
  INDEX `fk_Transfer_1_idx` (`source_organisation_id_ref` ASC) VISIBLE,
  INDEX `fk_Transfer_2_idx` (`destination_organisation_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Transfer_1`
    FOREIGN KEY (`source_organisation_id_ref`)
    REFERENCES `archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transfer_2`
    FOREIGN KEY (`destination_organisation_id_ref`)
    REFERENCES `archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`document_type_belongings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`document_type_belongings` ;

CREATE TABLE IF NOT EXISTS `archive`.`document_type_belongings` (
  `iddocument_type_belongings` INT NOT NULL AUTO_INCREMENT,
  `belonging_domain_id_ref` INT NULL,
  `belonging_type_id_ref` INT NULL,
  `belonging_code` VARCHAR(45) NULL,
  PRIMARY KEY (`iddocument_type_belongings`),
  INDEX `fk_document_type_belongings_1_idx` (`belonging_type_id_ref` ASC) VISIBLE,
  INDEX `fk_document_type_belongings_2_idx` (`belonging_domain_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_document_type_belongings_1`
    FOREIGN KEY (`belonging_type_id_ref`)
    REFERENCES `archive`.`Document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_type_belongings_2`
    FOREIGN KEY (`belonging_domain_id_ref`)
    REFERENCES `archive`.`Domain_Organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`session` ;

CREATE TABLE IF NOT EXISTS `archive`.`session` (
  `idsession` INT NOT NULL AUTO_INCREMENT,
  `session_start_date` DATE NULL,
  `session_end_date` DATE NULL,
  PRIMARY KEY (`idsession`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`trainee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive`.`trainee` ;

CREATE TABLE IF NOT EXISTS `archive`.`trainee` (
  `idtrainee` INT NOT NULL,
  `profile_ref_id` INT NULL,
  `session_ref_id` INT NULL,
  `trainee_mark` VARCHAR(45) NULL,
  `trainee_evaluation` VARCHAR(45) NULL,
  PRIMARY KEY (`idtrainee`),
  INDEX `fk_trainee_1_idx` (`profile_ref_id` ASC) VISIBLE,
  INDEX `fk_trainee_2_idx` (`session_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainee_1`
    FOREIGN KEY (`profile_ref_id`)
    REFERENCES `archive`.`Profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainee_2`
    FOREIGN KEY (`session_ref_id`)
    REFERENCES `archive`.`session` (`idsession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;