-- MySQL Script generated by MySQL Workbench
-- Di 11 Jul 2023 00:44:12 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Archive
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Archive` ;

-- -----------------------------------------------------
-- Schema Archive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Archive` ;
USE `Archive` ;

-- -----------------------------------------------------
-- Table `Archive`.`Domain_Organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Domain_Organisation` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Domain_Organisation` (
  `idDomain_Organisation` INT NOT NULL AUTO_INCREMENT,
  `Domain_Organisation_label_fr` VARCHAR(45) NULL,
  `Domain_Organisation_label_ar` VARCHAR(45) NULL,
  `Domain_Organisation_acronym_fr` VARCHAR(45) NULL,
  `Domain_Organisation_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idDomain_Organisation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Region` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Region` (
  `idRegion` INT NOT NULL AUTO_INCREMENT,
  `region_label_fr` VARCHAR(45) NULL,
  `region_label_ar` VARCHAR(45) NULL,
  `region_acronym_fr` VARCHAR(45) NULL,
  `region_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Sector` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Sector` (
  `idSector` INT NOT NULL AUTO_INCREMENT,
  `label_sector_fr` VARCHAR(45) NULL,
  `label_sector_ar` VARCHAR(45) NULL,
  `acronym_sector_fr` VARCHAR(45) NULL,
  `acronym_sector_ar` VARCHAR(45) NULL,
  `region_ref_id` INT NULL,
  PRIMARY KEY (`idSector`),
  INDEX `fk_Sector_1_idx` (`region_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sector_1`
    FOREIGN KEY (`region_ref_id`)
    REFERENCES `Archive`.`Region` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Organisation` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Organisation` (
  `id_Organisation` INT NOT NULL AUTO_INCREMENT,
  `Organisation_name_ar` VARCHAR(255) NULL,
  `Organisation_name_fr` VARCHAR(255) NULL,
  `ACRONYM_AR` VARCHAR(45) NULL,
  `ACRONYM_FR` VARCHAR(45) NULL,
  `Organisation_domain_id_ref` INT NULL,
  `sector_ref_id` INT NULL,
  PRIMARY KEY (`id_Organisation`),
  INDEX `fk_Organisation_1_idx` (`Organisation_domain_id_ref` ASC) VISIBLE,
  INDEX `fk_Organisation_2_idx` (`sector_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Organisation_1`
    FOREIGN KEY (`Organisation_domain_id_ref`)
    REFERENCES `Archive`.`Domain_Organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organisation_2`
    FOREIGN KEY (`sector_ref_id`)
    REFERENCES `Archive`.`Sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`doc_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`doc_reference` ;

CREATE TABLE IF NOT EXISTS `Archive`.`doc_reference` (
  `reference_id` INT NOT NULL AUTO_INCREMENT,
  `reference_year` INT NULL,
  `reference_ar` VARCHAR(45) NULL,
  `reference_fr` VARCHAR(45) NULL,
  `Organisation_id_Organisation` INT NULL,
  PRIMARY KEY (`reference_id`),
  INDEX `fk_doc_reference_Organisation1_idx` (`Organisation_id_Organisation` ASC) VISIBLE,
  CONSTRAINT `fk_doc_reference_Organisation1`
    FOREIGN KEY (`Organisation_id_Organisation`)
    REFERENCES `Archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Container`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Container` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Container` (
  `idContainer` INT NOT NULL AUTO_INCREMENT,
  `type_container` VARCHAR(45) NULL,
  PRIMARY KEY (`idContainer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`profile_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`profile_rank` ;

CREATE TABLE IF NOT EXISTS `Archive`.`profile_rank` (
  `idprofile_rank` INT NOT NULL AUTO_INCREMENT,
  `profile_rank_label_fr` VARCHAR(45) NULL,
  `profile_rank_label_ar` VARCHAR(45) NULL,
  `profile_rank_acronym_fr` VARCHAR(45) NULL,
  `profile_rank_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofile_rank`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Profile` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Profile` (
  `idProfile` INT NOT NULL AUTO_INCREMENT,
  `Profile_serial` VARCHAR(45) NULL,
  `Profile_rank_id_ref` INT NULL,
  `Profile_position_org` INT NULL,
  `Profile_domain_id_ref` INT NULL,
  PRIMARY KEY (`idProfile`),
  INDEX `fk_Profile_1_idx` (`Profile_rank_id_ref` ASC) VISIBLE,
  INDEX `fk_Profile_2_idx` (`Profile_position_org` ASC) VISIBLE,
  INDEX `fk_Profile_3_idx` (`Profile_domain_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_1`
    FOREIGN KEY (`Profile_rank_id_ref`)
    REFERENCES `Archive`.`profile_rank` (`idprofile_rank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_2`
    FOREIGN KEY (`Profile_position_org`)
    REFERENCES `Archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_3`
    FOREIGN KEY (`Profile_domain_id_ref`)
    REFERENCES `Archive`.`Domain_Organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Person` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Person` (
  `PERSON_ID` INT NOT NULL AUTO_INCREMENT,
  `Person_name` VARCHAR(45) NULL,
  `Person_lastname` VARCHAR(45) NULL,
  `Person_profile_id_ref` INT NULL,
  PRIMARY KEY (`PERSON_ID`),
  INDEX `fk_Person_1_idx` (`Person_profile_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Person_1`
    FOREIGN KEY (`Person_profile_id_ref`)
    REFERENCES `Archive`.`Profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`User` ;

CREATE TABLE IF NOT EXISTS `Archive`.`User` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NULL,
  `USER_PASSWORD` VARCHAR(255) NULL,
  `Person_ID` INT NULL,
  `admin_privilege` TINYINT NULL,
  PRIMARY KEY (`USER_ID`),
  INDEX `fk_User_Person_idx` (`Person_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Person`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Archive`.`Person` (`PERSON_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Document` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Document` (
  `Doc_ID` INT NOT NULL AUTO_INCREMENT,
  `Doc_Label` VARCHAR(255) NULL,
  `Doc_size` BIGINT NULL,
  `Doc_number_of_chunks` SMALLINT NULL,
  `reference_id` INT NOT NULL,
  `USER_ID` INT NULL,
  `Doc_chunk_number` SMALLINT NULL,
  `container_ref_id` INT NULL,
  `added_by_user_id_ref` INT NULL,
  PRIMARY KEY (`Doc_ID`, `reference_id`),
  INDEX `fk_Document_User1_idx` (`container_ref_id` ASC) VISIBLE,
  INDEX `fk_Document_reference1_idx` (`reference_id` ASC) VISIBLE,
  INDEX `fk_Document_1_idx` (`added_by_user_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Document_reference1`
    FOREIGN KEY (`reference_id`)
    REFERENCES `Archive`.`doc_reference` (`reference_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_User1`
    FOREIGN KEY (`container_ref_id`)
    REFERENCES `Archive`.`Container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_1`
    FOREIGN KEY (`added_by_user_id_ref`)
    REFERENCES `Archive`.`User` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Document_chunk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Document_chunk` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Document_chunk` (
  `idChunk` INT NOT NULL AUTO_INCREMENT,
  `Document_Doc_ID` INT NOT NULL,
  `Document_chunk_data` BLOB NULL,
  PRIMARY KEY (`idChunk`, `Document_Doc_ID`),
  INDEX `fk_Document_chunk_Document1_idx` (`Document_Doc_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Document_chunk_Document1`
    FOREIGN KEY (`Document_Doc_ID`)
    REFERENCES `Archive`.`Document` (`Doc_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Transcript` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Transcript` (
  `idTranscript` INT NOT NULL AUTO_INCREMENT,
  `reference_transcript` VARCHAR(45) NULL,
  PRIMARY KEY (`idTranscript`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Document_type` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Document_type` (
  `idDocument_type` INT NOT NULL AUTO_INCREMENT,
  `document_type_label_fr` VARCHAR(45) NULL,
  `document_type_label_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocument_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Elimination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Elimination` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Elimination` (
  `idElimination` INT NOT NULL AUTO_INCREMENT,
  `max_eliminated_date` DATE NULL,
  `min_eliminated_date` DATE NULL,
  `id_transcript` INT NOT NULL,
  `doc_type_ref` INT NOT NULL,
  `elimination_container_ref_id` INT NOT NULL,
  PRIMARY KEY (`idElimination`, `id_transcript`, `doc_type_ref`),
  INDEX `fk_Elimination_1_idx` (`doc_type_ref` ASC) VISIBLE,
  INDEX `fk_Elimination_2_idx` (`elimination_container_ref_id` ASC) VISIBLE,
  UNIQUE INDEX `id_transcript_UNIQUE` (`id_transcript` ASC) VISIBLE,
  UNIQUE INDEX `doc_type_ref_UNIQUE` (`doc_type_ref` ASC) VISIBLE,
  UNIQUE INDEX `elimination_container_ref_id_UNIQUE` (`elimination_container_ref_id` ASC) VISIBLE,
  CONSTRAINT `id_ref_transcript`
    FOREIGN KEY (`id_transcript`)
    REFERENCES `Archive`.`Transcript` (`idTranscript`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elimination_1`
    FOREIGN KEY (`doc_type_ref`)
    REFERENCES `Archive`.`Document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elimination_2`
    FOREIGN KEY (`elimination_container_ref_id`)
    REFERENCES `Archive`.`Container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Communication_demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Communication_demand` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Communication_demand` (
  `idCommunication_demand` INT NOT NULL AUTO_INCREMENT,
  `Communication_demanding_org_ref_id` INT NULL,
  PRIMARY KEY (`idCommunication_demand`),
  INDEX `fk_Communication_demand_1_idx` (`Communication_demanding_org_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Communication_demand_1`
    FOREIGN KEY (`Communication_demanding_org_ref_id`)
    REFERENCES `Archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Transfer` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Transfer` (
  `idTransfer` INT NOT NULL AUTO_INCREMENT,
  `source_organisation_id_ref` INT NULL,
  `destination_organisation_id_ref` INT NULL,
  `container_ref_id` VARCHAR(45) NULL,
  PRIMARY KEY (`idTransfer`),
  INDEX `fk_Transfer_1_idx` (`source_organisation_id_ref` ASC) VISIBLE,
  INDEX `fk_Transfer_2_idx` (`destination_organisation_id_ref` ASC) VISIBLE,
  UNIQUE INDEX `source_organisation_id_ref_UNIQUE` (`source_organisation_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_Transfer_1`
    FOREIGN KEY (`source_organisation_id_ref`)
    REFERENCES `Archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transfer_2`
    FOREIGN KEY (`destination_organisation_id_ref`)
    REFERENCES `Archive`.`Organisation` (`id_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`document_type_belongings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`document_type_belongings` ;

CREATE TABLE IF NOT EXISTS `Archive`.`document_type_belongings` (
  `iddocument_type_belongings` INT NOT NULL AUTO_INCREMENT,
  `belonging_domain_id_ref` INT NULL,
  `belonging_type_id_ref` INT NULL,
  `belonging_code` VARCHAR(45) NULL,
  PRIMARY KEY (`iddocument_type_belongings`),
  INDEX `fk_document_type_belongings_1_idx` (`belonging_type_id_ref` ASC) VISIBLE,
  INDEX `fk_document_type_belongings_2_idx` (`belonging_domain_id_ref` ASC) VISIBLE,
  CONSTRAINT `fk_document_type_belongings_1`
    FOREIGN KEY (`belonging_type_id_ref`)
    REFERENCES `Archive`.`Document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_type_belongings_2`
    FOREIGN KEY (`belonging_domain_id_ref`)
    REFERENCES `Archive`.`Domain_Organisation` (`idDomain_Organisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`session` ;

CREATE TABLE IF NOT EXISTS `Archive`.`session` (
  `idsession` INT NOT NULL AUTO_INCREMENT,
  `session_start_date` DATE NULL,
  `session_end_date` DATE NULL,
  PRIMARY KEY (`idsession`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`trainee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`trainee` ;

CREATE TABLE IF NOT EXISTS `Archive`.`trainee` (
  `idtrainee` INT NOT NULL AUTO_INCREMENT,
  `profile_ref_id` INT NULL,
  `session_ref_id` INT NULL,
  `trainee_mark` VARCHAR(45) NULL,
  `trainee_evaluation` VARCHAR(45) NULL,
  PRIMARY KEY (`idtrainee`),
  INDEX `fk_trainee_1_idx` (`profile_ref_id` ASC) VISIBLE,
  INDEX `fk_trainee_2_idx` (`session_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_trainee_1`
    FOREIGN KEY (`profile_ref_id`)
    REFERENCES `Archive`.`Profile` (`idProfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainee_2`
    FOREIGN KEY (`session_ref_id`)
    REFERENCES `Archive`.`session` (`idsession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Store` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `Storetype` VARCHAR(45) NULL,
  `store_label_fr` VARCHAR(45) NULL,
  `store_label_ar` VARCHAR(45) NULL,
  `store_acronym_fr` VARCHAR(45) NULL,
  `store_acronym_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idStore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Bay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Bay` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Bay` (
  `idBay` INT NOT NULL AUTO_INCREMENT,
  `Store_ref_id` INT NULL,
  `Bay_ref_fr` VARCHAR(45) NULL,
  `Bay_ref_ar` VARCHAR(45) NULL,
  PRIMARY KEY (`idBay`),
  INDEX `fk_Bay_1_idx` (`Store_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bay_1`
    FOREIGN KEY (`Store_ref_id`)
    REFERENCES `Archive`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Cob`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Cob` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Cob` (
  `idCob` INT NOT NULL AUTO_INCREMENT,
  `Cob_ref_fr` VARCHAR(45) NULL,
  `Cob_ref_ar` VARCHAR(45) NULL,
  `bay_ref_id` INT NULL,
  PRIMARY KEY (`idCob`),
  INDEX `fk_Cob_1_idx` (`bay_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cob_1`
    FOREIGN KEY (`bay_ref_id`)
    REFERENCES `Archive`.`Bay` (`idBay`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Shelf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Shelf` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Shelf` (
  `idShelf` INT NOT NULL AUTO_INCREMENT,
  `Shelf_ref_fr` VARCHAR(45) NULL,
  `Shelf_ref_ar` VARCHAR(45) NULL,
  `cob_ref_id` INT NULL,
  PRIMARY KEY (`idShelf`),
  INDEX `fk_Shelf_1_idx` (`cob_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Shelf_1`
    FOREIGN KEY (`cob_ref_id`)
    REFERENCES `Archive`.`Cob` (`idCob`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Cabinet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Cabinet` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Cabinet` (
  `idCabinet` INT NOT NULL AUTO_INCREMENT,
  `Cabinet_store_ref_id` INT NULL,
  `Cabinet_ref_ar` VARCHAR(45) NULL,
  `Cabinet_ref_fr` VARCHAR(45) NULL,
  PRIMARY KEY (`idCabinet`),
  INDEX `fk_Cabinet_1_idx` (`Cabinet_store_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cabinet_1`
    FOREIGN KEY (`Cabinet_store_ref_id`)
    REFERENCES `Archive`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Container_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Container_position` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Container_position` (
  `idContainer_position` INT NOT NULL AUTO_INCREMENT,
  `Container_position_shelf_ref_id` INT NULL,
  `Container_position_cabinet_ref_id` INT NULL,
  PRIMARY KEY (`idContainer_position`),
  INDEX `fk_Container_position_1_idx` (`Container_position_shelf_ref_id` ASC) VISIBLE,
  INDEX `fk_Container_position_2_idx` (`Container_position_cabinet_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Container_position_1`
    FOREIGN KEY (`Container_position_shelf_ref_id`)
    REFERENCES `Archive`.`Shelf` (`idShelf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Container_position_2`
    FOREIGN KEY (`Container_position_cabinet_ref_id`)
    REFERENCES `Archive`.`Cabinet` (`idCabinet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Contained_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Contained_types` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Contained_types` (
  `idContained_types` INT NOT NULL AUTO_INCREMENT,
  `container_type_ref_id` INT NULL,
  `types_contained_ref_id` INT NULL,
  `Container_position_ref_id` INT NULL,
  PRIMARY KEY (`idContained_types`),
  INDEX `fk_Contained_types_1_idx` (`container_type_ref_id` ASC) VISIBLE,
  INDEX `fk_Contained_types_2_idx` (`types_contained_ref_id` ASC) VISIBLE,
  INDEX `fk_Contained_types_3_idx` (`Container_position_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Contained_types_1`
    FOREIGN KEY (`container_type_ref_id`)
    REFERENCES `Archive`.`Container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contained_types_2`
    FOREIGN KEY (`types_contained_ref_id`)
    REFERENCES `Archive`.`Document_type` (`idDocument_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contained_types_3`
    FOREIGN KEY (`Container_position_ref_id`)
    REFERENCES `Archive`.`Container_position` (`idContainer_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Communication_response`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Communication_response` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Communication_response` (
  `idCommunication_response` INT NOT NULL AUTO_INCREMENT,
  `Communication_demand_ref_id` INT NULL,
  PRIMARY KEY (`idCommunication_response`),
  INDEX `fk_Communication_response_1_idx` (`Communication_demand_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Communication_response_1`
    FOREIGN KEY (`Communication_demand_ref_id`)
    REFERENCES `Archive`.`Communication_demand` (`idCommunication_demand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`Communication_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`Communication_subject` ;

CREATE TABLE IF NOT EXISTS `Archive`.`Communication_subject` (
  `idCommunication_subject` INT NOT NULL AUTO_INCREMENT,
  `Communicated_doc_ref_id` INT NULL,
  `Communication_response_ref_id` INT NULL,
  PRIMARY KEY (`idCommunication_subject`),
  INDEX `fk_Communication_subject_1_idx` (`Communication_response_ref_id` ASC) VISIBLE,
  INDEX `fk_Communication_subject_2_idx` (`Communicated_doc_ref_id` ASC) VISIBLE,
  CONSTRAINT `fk_Communication_subject_1`
    FOREIGN KEY (`Communication_response_ref_id`)
    REFERENCES `Archive`.`Communication_response` (`idCommunication_response`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Communication_subject_2`
    FOREIGN KEY (`Communicated_doc_ref_id`)
    REFERENCES `Archive`.`Document` (`Doc_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Archive`.`transferred_contained_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Archive`.`transferred_contained_types` ;

CREATE TABLE IF NOT EXISTS `Archive`.`transferred_contained_types` (
  `idtransferred_contained_types` INT NOT NULL AUTO_INCREMENT,
  `transferred_contained_types_id_ref` INT NULL,
  `transferred_types_contained` INT NULL,
  INDEX `fk_transferred_contained_types_1_idx` (`transferred_types_contained` ASC) VISIBLE,
  INDEX `fk_transferred_contained_types_2_idx` (`transferred_contained_types_id_ref` ASC) VISIBLE,
  PRIMARY KEY (`idtransferred_contained_types`),
  CONSTRAINT `fk_transferred_contained_types_1`
    FOREIGN KEY (`transferred_types_contained`)
    REFERENCES `Archive`.`Contained_types` (`idContained_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transferred_contained_types_2`
    FOREIGN KEY (`transferred_contained_types_id_ref`)
    REFERENCES `Archive`.`Transfer` (`idTransfer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
