version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-node
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
        - ./database.sql:/data/application/init.sql
        - ./data:/var/lib/mysql
    networks:
      - siman_net
volumes:
  data:
networks:
  siman_net:
    external: true